DECLARE
     V_EMPNO EMP.EMPNO%TYPE;
	 V_AMOUNT FLOAT;

BEGIN
    V_EMPNO := &EMPNO;
	V_AMOUNT:= &AMOUNT;
	
	UPDATE EMP
	SET SAL = SAL+V_AMOUNT
	WHERE EMPNO = V_EMPNO;
	
	COMMIT;
	
	
	DBMS_OUTPUT.PUT_LINE('SALARY UPDATED');
	DBMS_OUTPUT.PUT_LINE('UPDATE QUERY WITH TWO INPUT');
END;

/